name: my_wizard_name
menu_entry: "My wizard menu entry"
default_env: my_conda_env_name
use_vr: true

python_version: 3.9
pymol_version: 3.3.0
openvr_version: 1.0.17

pre_script: "my_pre_installation_script.py"
post_script: "my_post_installation_script.py"
